logging:
  level:
    # Feign 的请求日志只在 DEBUG 级别输出，必须把对应包开到 DEBUG
    com.zjc.consumer.feign: debug
    com.zjc.common.api: debug

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
            connectTimeout: 1000
            readTimeout: 2000
feign:
  # 熔断降级
  sentinel:
    enabled: true
