spring:
  cloud:
    nacos:
      config:
        server-addr: 192.168.100.128:8848
        file-extension: yaml
        username: nacos
        password: nacos
      discovery:
        server-addr: 192.168.100.128:8848
        username: nacos
        password: nacos
  config:
    import:
      - nacos:${spring.profiles.active}?group=${spring.application.name}&namespace=public&refreshEnabled=true
