spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    openfeign:
      client:
        config:
          default:
            loggerLevel: basic
            connectTimeout: 3000
            readTimeout: 5000
  config:
    import:
      - nacos:prod?group=service-consumer&namespace=public&refreshEnabled=true

feign:
  sentinel:
    enabled: true

logging:
  level:
    com.zjc.consumer.feign: info
    com.zjc.common.api: info
