zjc:
  config:
    env: ${app.env:dev}
    source: ${app.config.source:local}
  infrastructure:
    host: ${INFRASTRUCTURE_HOST:129.204.226.206}

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${zjc.infrastructure.host}:8848
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
