server:
  port: 9001

spring:
  application:
    name: service-provider
  profiles:
    active: ${zjc.config.env},${zjc.config.source}
    group:
      local:
        - api
        - jasypt
        - zipkin
