server:
  port: 9001

spring:
  application:
    name: service-provider
  profiles:
    active: dev
    include:
      - db
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import:
      - nacos:dev?group=service-provider&namespace=public&refreshEnabled=true
      - nacos:pub?group=service-provider&namespace=public&refreshEnabled=true