server:
  port: 9004

spring:
  application:
    name: service-mail
  mail:
    host: smtp.email.cn
    port: 465
    username: jiancai.zhong@email.cn
    password: ENC(rgWg9f0/hLk7WCJq8pCJcQEvK0Cb5+Er0CDXL1kBGZE=)
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${zjc.infrastructure.host}:3306/spring_cloud_alibaba?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&sslMode=REQUIRED
    username: spring_cloud_alibaba
    password: ENC(+JelvFJgFGin7M1gETrpUDP+uVrbI2Fc6IXDewsY6Zw=)

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.zjc.mail
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted