spring:
  cloud:
    nacos:
      config:
        server-addr: 129.204.226.206:8848
        file-extension: yaml
        username: nacos
        password: nacos
      discovery:
        server-addr: 129.204.226.206:8848
        username: nacos
        password: nacos
  config:
    import:
      - nacos:${zjc.config.env}?group=${spring.application.name}&namespace=public&refreshEnabled=true
      - nacos:jasypt?group=spring-cloud-alibaba-public&namespace=public&refreshEnabled=true
      - nacos:api?group=spring-cloud-alibaba-public&namespace=public&refreshEnabled=true
      - nacos:zipkin?group=spring-cloud-alibaba-public&namespace=public&refreshEnabled=true
