spring:
  cloud:
    nacos:
      config:
        server-addr: ${zjc.infrastructure.host}:8848
        file-extension: yaml
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - nacos:prod?group=${spring.application.name}&namespace=public&refreshEnabled=true
