server:
  port: 9001

spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://${zjc.infrastructure.host}:3306/spring_cloud_alibaba?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: spring_cloud_alibaba
    password: ENC(vStS7aXxtuaitgTfFqkF4DevOB1cYe4pkfNFJCdIWSo=)

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.zjc.provider
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false