server:
  port: 9004

spring:
  application:
    name: service-mail
  profiles:
    active: dev
    include:
      - nacos


# Actuator 端点暴露（供 SBA 采集监控数据）
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
