server:
  port: 9004

spring:
  application:
    name: service-mail
  profiles:
    active: dev
    include:
      - nacos

management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
    export:
      zipkin:
        enabled: ${ZIPKIN_EXPORT_ENABLED:true}
        endpoint: "${ZIPKIN_ENDPOINT:http://129.204.226.206:9411/api/v2/spans}"
      enabled: ${TRACING_ENABLED:true}
