server:
  port: 9004

spring:
  application:
    name: service-mail
  profiles:
    active: dev
    include:
      - api
      - jasypt
      - zipkin
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
      config:
        enabled: false
