spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.204.226.206:8848
  mail:
    host: 129.204.226.206
    port: 1025
    username: dev@localhost
    password: ""
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            enable: false
          starttls:
            enable: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.204.226.206:3306/spring_cloud_alibaba?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&sslMode=REQUIRED
    username: spring_cloud_alibaba
    password: ENC(MWH6hl4MZQrWG5AAAlOz6GEckzQiscn7JS4PGjb22oAGgkIo2bRsX2yBTebFOKP9T2gCra9uooBZN/SetNnnaQ==)

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://129.204.226.206:9411/api/v2/spans

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.zjc.mail
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
